# NumPy: Arrays and Vectorized Computations
## DAT540 Introduction to Data Science
## University of Stavanger
### L04
#### Antorweep Chakravorty (antorweep.chakravorty@uis.no)

- **NumPy** or *Numerical Python*, is one of the most important foundational package for numerical computing in python
 - *ndarray*, an efficient multidimensional array provides fast array-oriented arithmetic operations and flexible *broadcasting* capabilities
 - Mathematical functions for fast operations on entire array of data without having to write loops
 - Tools for reading/writing array data to disk and working with memory-mapped files
 - Linear algebra, random number generation and Fourier transform capabilities
 - A C-API for connecting NumPy with libraries written in C, C++, or FORTRAN
 - NumPy C-API allows data to be easily passed to external libraries written in a low-level language and for external libraries to return data to python as NumPy arrays

  - The main areas of functionality for the use of NumPy arrays for data analysis:
    - Fast vectorized array operations for data mugging and cleaning, sub-setting, and filtering, transformation, and any kinds of computations
    - Common array algorithms like sorting, unique, and set operations
    - Efficient descriptive statistics and aggregating/summarizing data
    - Data alignment and relational data manipulation for merging and joining heterogeneous datasets
    - Expressing conditional logic as array expressions instead of loops 
    - Group-wise data manipulations (aggregation, transformation, function application)

- NumPy based algorithms are generally 10 to 100 times faster than their pure python counterparts and use significantly less memory

In [2]:
import numpy as np
#million numbers
n = 1000000
my_arr = np.arange(n)
my_list = list(range(n))
# Now let us multipy each sequence by 2

In [3]:
import sys
print(sys.getsizeof(my_arr)) #bytes
%timeit my_arr * 2

8000096
956 µs ± 67.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
print(sys.getsizeof(my_list)) #bytes
%timeit [x * 2 for x in my_list]

9000112
50.6 ms ± 1.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


- **ndarray** a multidimensional array object that provides a fast and flexible container for large homogeneous datasets

In [5]:
import numpy as np
data = np.random.randn(2,3)
data

array([[-1.15222223,  0.99230019,  0.18427945],
       [ 0.47449334,  0.21408703, -2.81126005]])

 - ndarrays also allows direct scalar and matrix operations 

In [6]:
print(data * 10)
print('-' * 100)
print(data + data)

[[-11.52222227   9.92300192   1.84279452]
 [  4.74493337   2.14087026 -28.11260048]]
----------------------------------------------------------------------------------------------------
[[-2.30444445  1.98460038  0.3685589 ]
 [ 0.94898667  0.42817405 -5.6225201 ]]


 - Each ndarray has a *shape* tuple describing the size dimensions, and  *dtype*, object describing the data type 

In [7]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


 - ndarray can be created using the **array** function
 - It accepts any sequence-like object (including other arrays) and produces a new numpy array containing the passed data

```python
data1 = [6,7.5,8,0,1]
arr1 = np.array(data)
```
 - Nested sequences, like a list of equal-length list, will also be converted into a multidimensional array

```python
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
```
 - What will be shape of arr2?
 - Additionally to *np.array*, there are other functions for creating new arrays.
 - **zeros** and **ones** create arrays of 0s or 1s respectively
 - **empty** would create an array that contains zeros, ones or garbage values

In [9]:
print(np.zeros(10))
print('-' * 100)
print(np.zeros((2,4))) # multidimentional
print('-' * 100)
print(np.ones(10))
print('-' * 100)
print(np.empty(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
----------------------------------------------------------------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------------------------------------------------------------------------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
----------------------------------------------------------------------------------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


  - **arange** is an array-valued version of built-in python *range* function

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

  - Array creation functions
  <img src='arr_creation_func.png'>

- *NumPy* - a multidimensional array object
  - **Data Types**
    - *dtype* is a special object containing the information / meta-data about the objects stored in a ndarray
    - dtypes provide mapping directly onto an underlying disk or memory representation
    - Allows easy read and write of binary stream of data to disk and to connect to code written in a low level language like C
    <img src='numpy_datatypes.png'>

  - A NumPy array can be converted or casted from one dtype to another using the ndarray's **astype** method
  - astype accepts a NumPy data type or the dtype of an existing ndarray
  - Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype

In [1]:
import numpy as np
arr = np.arange(5)
print(arr.dtype)
arr = arr.astype(np.float64)
print(arr.dtype)

int64
float64


- **Pseudorandom Number Generator**
  - The numpy.random module supplements the build-in python random with functions for efficiency generating whole arrays of sample values from many kinds of probability distributions
  - They are termed as pseudorandom numbers because they are generated by an algorithm with deterministic behavior based on the *seed* of the random number generator
  - The data generation functions in numpy.random use a global random seed
  
  ```python
  import numpy as np
  np.random.seed(123)
  np.random.normal(size=(4,4))
  ```
  - To avoid global state, *numpy.random.RandomState* can be used to create a random number generator isolated from other
  
  ```python
  import numpy as np
  rgn = np.random.RandomState(1234)
  rgn.normal(size=(4,4))
  ```
<img src='np_random.png' width='450'>
  

 - Arithmetic Operations
   - ndarray offers *vectorization*, that is allow batch operation on data without writing any for loops
   - Any arithmetic operations between equal size arrays applies the operation element wise
   - Operations with scalars propagate the scalar argument to each element in the array
   - Comparisons between arrays of same size yields boolean arrays
   - Operations between different sized arrays is called broadcasting

In [2]:
# Operation between two equally sized arrays
arr1 = np.arange(4).reshape(2,2) # reshape shapes the array into the given share
arr2 = np.arange(4, 8).reshape(2,2) # Here arange is generating numbers from 4 until 8
print('arr1 shape:', arr1.shape)
print('arr2 shape:', arr2.shape)

# Operation between equal sized arrays are applied element wise
result1 = arr1 * arr2
print('op: arr1 * arr2')
print(result1)
print('op: arr1 - arr2')
result2 = arr1 - arr2
print(result2)

arr1 shape: (2, 2)
arr2 shape: (2, 2)
op: arr1 * arr2
[[ 0  5]
 [12 21]]
op: arr1 - arr2
[[-4 -4]
 [-4 -4]]


In [3]:
# Operation with scalars propagate the scalar argument to each element in the array
result3 = arr1 / 10
print('op: arr1 / 10')
print(result3)

# Comparisions between arrays of same size yields a boolean array
np.random.seed(12345) # A random seed is a number used to initialize a pseudorandom number generator. 
arr3 = np.random.randint(-100, 100, size=4).reshape(2,2) # randint is used to generate random ints. args are low, high and size
arr4 = np.random.randint(-100, 100, size=4).reshape(2,2) # reshape is used to structure a sequence on number into a shape
result4 = arr4 > arr3
print('op: arr4 > arr3')
print(result4)

op: arr1 / 10
[[0.  0.1]
 [0.2 0.3]]
op: arr4 > arr3
[[ True False]
 [False False]]


 - **Basic Indexing and Slicing**
   - Indexing and slicing on one dimensional ndarrays are similar to python lists on the surface
   - If an scalar value is assigned to a slice, arr[5:8] = 12, the value is propagated (or broadcasted) to the entire section
   - What happens if you do a bare slice assignment: arr[:] = 12 
   - Array slice on ndarrays are views on the original array. The data does not get replicated or copied and any changes to the slice or view gets reflected to the original array
   - A copy of a array slice can be created using *copy.copy* or directly the **copy** method of any dnarray   

In [4]:
#Basic Indexing and Slicing
arr = np.arange(10)
print('arr: ', arr)
arr[5:8] = 12
print('arr: ', arr)

arr:  [0 1 2 3 4 5 6 7 8 9]
arr:  [ 0  1  2  3  4 12 12 12  8  9]


In [5]:
import copy
arr1 = copy.copy(arr[1:4])
arr1[0] = 99
arr2 = arr[7:10].copy()
arr2[:] = 100
print('arr1: ', arr1)
print('arr2: ', arr2)
print('arr: ', arr)

arr1:  [99  2  3]
arr2:  [100 100 100]
arr:  [ 0  1  2  3  4 12 12 12  8  9]


   - Elements in a multidimensional ndarray can be accessed directly by passing a comma separated list of indices to select individual elements
<img src='numpy_indexing.png' width='250'>

In [6]:
# accessing multidimentional arrays
arr2d = np.random.randint(0, 100, 4).reshape(2,2)
print('arr2d[0][1]=', arr2d[0][1], ' is same as arr2d[0,1]=', arr2d[0,1])

arr2d[0][1]= 59  is same as arr2d[0,1]= 59


In [7]:
arr3d = np.random.randint(0, 100, 8).reshape(2,2,2)
print('arr3d:\n', arr3d)
print('2x2 array:\n', arr3d[0])
print('1x2 array:\n', arr3d[0, 1])
print('indivisual element:', arr3d[0, 1, 1])

arr3d:
 [[[80 73]
  [11 77]]

 [[10 81]
  [82 38]]]
2x2 array:
 [[80 73]
 [11 77]]
1x2 array:
 [11 77]
indivisual element: 77


   - Modifying and copying slices in a multidimensional array

   - **Indexing with slices**'
    - 1d ndarrays can be slices in similar fashion to that of normal python lists
    - multi-dimensional arrays can be sliced on each **axis** generating a view on a sub-array or element
    - *axis* are the dimensions on a ndarray. For example a 3d array has 3 axes. 

In [8]:
np.random.seed(123)
arr1d = np.random.randint(0, 100, 5)
print(arr1d[1:4]) # get all elements from index 1 until index 4

[92 98 17]


In [9]:
# Two dimentional array slicing
arr2d = np.random.randint(0, 100, 9).reshape(3,3)
print('complete arr2d:\n', arr2d)
print('sliced arr2d[:2]\n', arr2d[:2]) # get all sub-arrays from index 0 until index 2 on axis 0

complete arr2d:
 [[57 86 97]
 [96 47 73]
 [32 46 96]]
sliced arr2d[:2]
 [[57 86 97]
 [96 47 73]]


In [10]:
# get all sub-arrays from index 0 until index 2 on axis 0 and from index 1 until index 3 on axis 1
print('sliced arr2d[:2, 1:3]\n', arr2d[:2, 1:3]) 

sliced arr2d[:2, 1:3]
 [[86 97]
 [47 73]]


<img src='2darray_slicing.png' width='150'>

In [11]:
#Swapping Values
np.random.seed(123)
arr3d = np.random.randint(0, 100, 8).reshape(2,2,2)
print('arr3d (original):\n', arr3d)
# Swapping values at arr3d[0,0] with arr3d[1,1]
temp = arr3d[0,0]
arr3d[0,0] = arr3d[1,1] # assigning a multi-dimentional sequence
arr3d[1,1] = temp # is it a success?

arr3d (original):
 [[[66 92]
  [98 17]]

 [[83 57]
  [86 97]]]


In [12]:
print('arr3d (swapped):\n', arr3d) # Why?

arr3d (swapped):
 [[[86 97]
  [98 17]]

 [[83 57]
  [86 97]]]


In [13]:
#Swapping Values
np.random.seed(123)
arr3d = np.random.randint(0, 100, 8).reshape(2,2,2)
print('arr3d (original):\n', arr3d)
# Swapping values at arr3d[0,0] with arr3d[1,1]. The right way
temp = arr3d[0,0].copy() # store a copy
arr3d[0,0] = arr3d[1,1] # assigning a multi-dimentional sequence
arr3d[1,1] = temp 
print('arr3d (swapped):\n', arr3d)

arr3d (original):
 [[[66 92]
  [98 17]]

 [[83 57]
  [86 97]]]
arr3d (swapped):
 [[[86 97]
  [98 17]]

 [[83 57]
  [66 92]]]


In [14]:
# What happens when we only swap a single element
# Swapping values at arr3d[0,0,0] with arr3d[1,1,1] and vice versa
np.random.seed(123)
arr3d = np.random.randint(0, 100, 8).reshape(2,2,2)
print('arr3d (original):\n', arr3d)

temp = arr3d[0,0,0]
arr3d[0,0,0] = arr3d[1,1,1] # assigning a single element
arr3d[1,1,1] = temp

arr3d (original):
 [[[66 92]
  [98 17]]

 [[83 57]
  [86 97]]]


In [15]:
print('arr3d (swapped):\n', arr3d)

arr3d (swapped):
 [[[97 92]
  [98 17]]

 [[83 57]
  [86 66]]]


  - **Boolean Indexing**
  

In [6]:
np.random.seed(123)
data = np.random.randn(7, 4) # randn function generates some random normally distributed data. args: d1, d2, ... describes the shape of the returned array
names = np.array(['Bob', 'Bob', 'Will', 'Joe', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Bob', 'Will', 'Joe', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [7]:
data

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904],
       [-1.25388067, -0.6377515 ,  0.9071052 , -1.4286807 ]])

   - Let each name corresponds to a row in the data array
   - We want to select all rows with corresponding name 'Bob'
   - Like arithmetic operations, comparisons (eg. ==) with arrays are also vectorized, returning a boolean array

In [8]:
names == 'Bob'

array([ True,  True, False, False, False, False, False])

   - The boolean array can be passed when indexing the array

In [9]:
data[names == 'Bob']

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263]])

   - The boolean array must be of the same length as the array axis it's indexing
   - Boolean array for indexing can be also combined with other boolean arrays or even other sequences for slicing an array on different axis

In [10]:
data[names == 'Bob', 2:3]

array([[ 0.2829785 ],
       [-2.42667924]])

   - To select everything but 'Bob', we can use the operators **\~**  or **!**

In [11]:
print(data[names != 'Bob'])
print(' ')
print(data[~ (names == 'Bob')])

[[ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904]
 [-1.25388067 -0.6377515   0.9071052  -1.4286807 ]]
 
[[ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904]
 [-1.25388067 -0.6377515   0.9071052  -1.4286807 ]]


   - Multiple boolean conditions can be combined using the **&** (and) or **|** (or) symbols

In [12]:
print(data[(names == 'Bob') | (names == 'Will')])

[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]]


In [13]:
np.random.seed(123)
data = np.random.randn(7, 4)
print(names == 'Bob')
data1 = data[0:2, 1:3] #Bob is present on axis=0 indices 0 and 1. Using basic indexing here
data1[:] = -1

[ True  True False False False False False]


In [14]:
print('data:\n', data)
print('data1:\n', data1)

data:
 [[-1.0856306  -1.         -1.         -1.50629471]
 [-0.57860025 -1.         -1.         -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904]
 [-1.25388067 -0.6377515   0.9071052  -1.4286807 ]]
data1:
 [[-1. -1.]
 [-1. -1.]]


In [15]:
data2 = data[names == 'Bob', 1:3]
data2[:] = 0

In [16]:
print('data:\n', data)
print('data2:\n', data2)

data:
 [[-1.0856306  -1.         -1.         -1.50629471]
 [-0.57860025 -1.         -1.         -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904]
 [-1.25388067 -0.6377515   0.9071052  -1.4286807 ]]
data2:
 [[0. 0.]
 [0. 0.]]


   - Selecting data from an array by boolean indexing always creates a **copy** of the data even if the array is unchanged

 - **Fancy Indexing**
    - Fancy indexing is used to describe indexing using integers arrays

In [27]:
# Creating a 8x4 array where each row has the index number as value for all its columns
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [28]:
# Slicing using fancy indexing on axis=0
arr[[1,3,2]] # What do you observe here?

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.]])

In [29]:
# Using negative indices
arr[[-1,-3,-2]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

   - Passing a multidimensional array to slice on multiple axis results in a one dimensional array of elements corresponding to each tuple of indices
   - the shape of the arrays for each axis needs to be the same or scalar for all but array on axis=0

In [30]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
arr[[1,3,2], [0,3,2]]

array([ 4, 15, 10])

   - In order to get the slice on each axis using multidimensional arrays, first select the rows(axis=0) and for those rows do indexing on the columns(axis=1) and so forth, it can be done as follows:

In [32]:
arr[[1,3,2]][:,[0,3,2]]

array([[ 4,  7,  6],
       [12, 15, 14],
       [ 8, 11, 10]])

   - Like **boolean indexing**, **fancy indexing** also creates a *copy* of the array

 - **Transposing Arrays and Swapping Axes**
   - Transposing is a form of reshaping that returns a view on the underlying data without copying.
   - Arrays have the *transpose* method and also the special attribute *T*

In [33]:
arr = np.arange(15).reshape(3,5)
print('arr:\n', arr)
print('arr.T:\n', arr.T) # rows become cols and cols become rows. The shape also changes

arr:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
arr.T:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


   - Transposing is useful while performing matrix computations.
   - For example, the inner matrix product can be computed using np.dot

In [34]:
arr = np.random.randn(2,2)
np.dot(arr, arr.T)

array([[0.76224075, 2.44750214],
       [2.44750214, 7.89744224]])

   - For higher dimensional arrays, *transpose* might also accept a tuple of axis numbers to permute the axes
   

In [35]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
# Transpose without any arguments acts the same way as T. It also means that we are transposing on all axis
arr.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [37]:
print('arr:\n', arr)
# If we want to transpose on only certain axis
arr.transpose((1,0,2)) # Here we transpose only axis 0 and 1 and keep 2 unchanged

arr:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

   - **swapaxes** is a method that takes a pair of axis numbers and switches the indicated axes to rearrange the data

In [38]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
arr.swapaxes(0,1) # same as arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

- Universal Functions (*ufunc*): Fast Element Wise Array Functions
  - Performs element wise operations on data in ndarrays
  - They act as vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results
  - Most ufuncs are simple element wise transformations on an array, like sqrt or exp and are called as *unary* ufuncs
<img src='unary_ufuncs.png' width='400'>

In [40]:
arr = np.arange(5)
print('arr: ', arr)
print('np.sqrt: ', np.sqrt(arr))
print('np.exp: ', np.exp(arr))


arr:  [0 1 2 3 4]
np.sqrt:  [0.         1.         1.41421356 1.73205081 2.        ]
np.exp:  [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


   - *binary* ufuncs take two arrays and return a single array as result, like maximum or add
<img src='binary_ufuncs.png' width='250'>

In [41]:
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x,y)

array([-0.80536652, -0.69987723,  0.92746243,  0.57380586,  0.33858905,
        0.68822271,  2.39236527,  0.41291216])

   - There are also ufuncs that can return multiple arrays, like modf that returns fractional and integral parts of a floating point array

In [42]:
arr = np.random.randint(1, 10, 10) * 5.7
remainder, whole_part = np.modf(arr)
print('arr: ', arr)
print('remainder: ', remainder)
print('whole_part: ', whole_part)

arr:  [11.4 17.1 11.4 11.4 22.8 34.2  5.7 51.3 11.4 39.9]
remainder:  [0.4 0.1 0.4 0.4 0.8 0.2 0.7 0.3 0.4 0.9]
whole_part:  [11. 17. 11. 11. 22. 34.  5. 51. 11. 39.]


  - ufunc instance methods
    - Each NumPy binary ufuncs has special methods for performing certain kinds of special vectorized operations
<img src='ufuncs_instance_methods.png'>

In [43]:
# reduce takes a single array and aggregates its values, optionally along an axis, by performing a sequence of binary operations
# sum elements in an array
arr = np.arange(10)
np.add.reduce(arr)

45

In [17]:
import numpy as np
# A trivial use case would be to check whether the values in each row of an array are sorted
arr = np.random.randint(1,1000, 40).reshape(8,5)
# array[::y] gets every yth element from the array
# array[x::y] gets every yth element starting at position x
arr[::2].sort() # sort few rows
arr

array([[107, 419, 577, 838, 844],
       [827, 395, 791, 718, 147],
       [159, 272, 412, 485, 766],
       [181, 583, 366, 372, 155],
       [245, 256, 391, 721, 783],
       [360, 972, 951, 968, 130],
       [187, 358, 538, 556, 696],
       [435, 981, 825, 306, 781]])

In [18]:
arr[:, :-1] <= arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False, False,  True]])

In [47]:
# accumulate produces an array of same size with the intermediate accumulated or cumulative sum values
arr = np.arange(4).reshape(2,2)
print('arr:\n', arr)
print('np.add.accumulate(arr)\n:', np.add.accumulate(arr)) 
print('np.add.accumulate(arr, axis=1)\n:', np.add.accumulate(arr, axis=1)) 

arr:
 [[0 1]
 [2 3]]
np.add.accumulate(arr)
: [[0 1]
 [2 4]]
np.add.accumulate(arr, axis=1)
: [[0 1]
 [2 5]]


In [20]:
# repeate duplicates values on specified indices and axis
arr = np.arange(3).repeat([1,2,2])
arr

array([0, 1, 1, 2, 2])

In [21]:
arr

array([0, 1, 1, 2, 2])

In [49]:
# outer performs a pairwise cross-product between two arrays
arr1 = np.arange(3)
np.multiply.outer(arr, arr1) # outer will have a dimension that is the sum of the dimensions of the inputs

array([[0, 0, 0],
       [0, 1, 2],
       [0, 1, 2],
       [0, 2, 4],
       [0, 2, 4]])

In [50]:
# reduceat performs local reduce, in essence an array groupby operation in which slices of the array are aggregated together
# it accepts a sequence of "bin edges" that indicates how to split and aggrregate the values
arr = np.arange(10)
# The results are the reductions performed over arr[0:5], arr[5:8], and arr[8:]
# As with other methods, the axis argument can also be passed
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

  - Writing new ufuncs in python
    - **numpy.frompyfunc** accepts a python function along with a specification for number of inputs and outputs

In [51]:
# Creating a add element-wise function
def add_elements(x, y):
    return x + y

add_them = np.frompyfunc(add_elements, 2, 1) # we could also use a lambda function instead of add_elements
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

    - The function provide a way to create ufunc like functions
    - However, in reality, they are very slow as they require a python function call to compute each element rather than NumPy's C-based ufunc loops
    - Alternatively, we could utilize NumPy C API to create such ufuncs aswell.

In [52]:
arr = np.random.randn(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

1.82 ms ± 19.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.63 µs ± 43.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


- [The **Numba** project ](http://numba.pydata.org)
  - Write fast NumPy functions using CPUs and GPUs
  - It uses the [LLVM](http://llvm.org) to translate python code into compiled machine code
  - In order to convert a python function to numba we have to use a decorator
  - The resulting function in many cases can run faster than vectorized NumPy versions
  - However, Numba cannot compile arbitrary python code, but it supports a significant subset of pure python

In [53]:
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count
x = np.random.randn(1000000)
y = np.random.randn(1000000)
%timeit mean_distance(x, y)
%timeit (x - y).mean()

405 ms ± 5.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.52 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


    - The NumPy version is over 100 times faster
    - Using **numba.jit** function we can turn the *mean_distance* function into a compiled Numba function

In [54]:
from numba import jit

# We use a  decorator here to convert the function to jit
# Alternatively, an existing python function can be converted to jit using jit function, then we do not have to use the decorator to define the function
#  eg.: numba_mean_distance = jit(mean_distance)
@jit 
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count
x = np.random.randn(1000000)
y = np.random.randn(1000000)
%timeit mean_distance(x, y)
%timeit (x - y).mean()

1.11 ms ± 69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.65 ms ± 90.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


  - Numba can also be used to create custom numpy.ufuncs using **numba.vectorize** function
  - Transforming: ufunc add_elements to Numba

In [55]:
from numba import vectorize
@vectorize
def add_elements(x, y):
    return x + y

In [56]:
arr = np.random.randn(1000000)
%timeit add_elements(arr, arr)
%timeit np.add(arr, arr)

673 µs ± 36.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
470 µs ± 32.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
